### ISSUE TITLE
[Meta] Submission listing: api dependencies

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#10011]
Meta issue just to track various outstanding issues for API adjustments that are required to power new submission 
listing.

Bold are priority issues.

### Missing data
- [x] **reviewMethod, reviewerName** on `/_submissions` endpoint in reviewAssignments array - https://github.com/pkp/pkp-lib/issues/9965
- [x] as reviewer - I am getting all the reviewAssignments in the /submission/ endpoint. Thats needs to be adjusted to only assigned and open ones - https://github.com/pkp/pkp-lib/issues/9965
- [x] **statusId & publication locale on** `_submissions/reviewerAssignments` - https://github.com/pkp/pkp-lib/issues/9825
- [x] **expose publication form via API** - https://github.com/pkp/pkp-lib/issues/10336
- [x] **Add stage assignment metadata to /participants** - https://github.com/pkp/pkp-lib/issues/10280  @ewhanson 
- [x] **Exposing metadataLocale in submission** - https://github.com/pkp/pkp-lib/issues/10329 @bozana 
- [x]  **Additional fields in submission schema** -  https://github.com/pkp/pkp-lib/issues/10480 @Vitaliy-1 
- [x] **Expose emailEntry API** - https://github.com/pkp/pkp-lib/issues/10412
- [x] **Improve decision API** - https://github.com/pkp/pkp-lib/issues/10465
- [x] **Add available editorial Decisions to API** - https://github.com/pkp/pkp-lib/issues/10537
- [x] reviewAssignments that are cancelled/declined are filtered out - https://github.com/pkp/pkp-lib/issues/10076 @Vitaliy-1 
- [x] add REVIEW_ASSIGNMENT_STATUS_VIEWED status - https://github.com/pkp/pkp-lib/issues/9799 @Vitaliy-1 
- [x] review assignment date of confirmation - https://github.com/pkp/pkp-lib/issues/10359
- [x] LoginAs & Gossip for reviewers and Login as for Paritcipants - https://github.com/pkp/pkp-lib/issues/10290

### Views adjustments
- [x] New Review Assignment listing: reviewer-assignments-all view returns also published submissions https://github.com/pkp/pkp-lib/issues/10009
- [x] New submission listing: assigned-to-me View should include authors? https://github.com/pkp/pkp-lib/issues/10010

### Other submission listing backend Improvements
- [x] Set dates when resending request - https://github.com/pkp/pkp-lib/issues/4789
- [x] Editorial activity additional information https://github.com/pkp/pkp-lib/issues/8885
- [x]  Removing Cancel Review Assignment https://github.com/pkp/pkp-lib/issues/9948

**Comment by Vitaliy-1** [comment]
@jardakotesovec, can you describe in more details this one:

> as reviewer - I am getting all the reviewAssignments in the /submission/ endpoint. Thats needs to be adjusted to only assigned and open ones - https://github.com/pkp/pkp-lib/issues/9965

I'm unable to reproduce the problem. I'm calling `...publicknowledge/api/v1/submissions` as a reviewer and don't retrieve any reviews. Response example:
```json
{
    "itemsMax": 8,
    "items": [
        {
            "_href": "http://localhost:8000/index.php/publicknowledge/api/v1/submissions/19",
            "contextId": 1,
            "currentPublicationId": 20,
            "dateLastActivity": "2024-06-06 05:35:00",
            "dateSubmitted": "2024-06-06 05:34:30",
            "editorAssigned": true,
            "id": 19,
            "lastModified": "2024-06-06 05:34:30",
            "locale": "en",
            "publications": [
                {
                    "_href": "http://localhost:8000/index.php/publicknowledge/api/v1/submissions/19/publications/20",
                    "authorsString": "",
                    "authorsStringIncludeInBrowse": "",
                    "authorsStringShort": "",
                    "categoryIds": [],
                    "coverImage": {
                        "en": null,
                        "fr_CA": null
                    },
                    "datePublished": null,
                    "doiObject": null,
                    "fullTitle": {
                        "en": "Finocchiaro: Arguments About Arguments",
                        "fr_CA": ""
                    },
                    "galleys": [],
                    "id": 20,
                    "locale": "en",
                    "pages": null,
                    "prefix": {
                        "en": "",
                        "fr_CA": ""
                    },
                    "primaryContactId": 28,
                    "pub-id::publisher-id": null,
                    "sectionId": 2,
                    "status": 1,
                    "submissionId": 19,
                    "subtitle": {
                        "en": "",
                        "fr_CA": ""
                    },
                    "title": {
                        "en": "Finocchiaro: Arguments About Arguments",
                        "fr_CA": ""
                    },
                    "urlPublished": "http://localhost:8000/index.php/publicknowledge/en/article/view/19/version/20",
                    "version": 1
                }
            ],
            "recommendationsIn": null,
            "reviewersNotAssigned": true,
            "revisionsRequested": false,
            "revisionsSubmitted": false,
            "scheduledIn": null,
            "stageId": 4,
            "status": 1,
            "statusLabel": "Queued",
            "submissionProgress": "",
            "urlAuthorWorkflow": "http://localhost:8000/index.php/publicknowledge/en/authorDashboard/submission/19",
            "urlEditorialWorkflow": "http://localhost:8000/index.php/publicknowledge/en/workflow/access/19",
            "urlPublished": "http://localhost:8000/index.php/publicknowledge/en/article/view/19",
            "urlSubmissionWizard": "http://localhost:8000/index.php/publicknowledge/en/submission?id=19",
            "urlWorkflow": "http://localhost:8000/index.php/publicknowledge/en/reviewer/submission/19"
        },
        ...
    ]
}
```

**Comment by jardakotesovec** [comment]
@Vitaliy-1 I meant endpoint for specific submission - index.php/publicknowledge/api/v1/submissions/12

**Comment by Vitaliy-1** [comment]
Author and reviewers have access to that endpoint, which includes information about reviews. If the review isn't open, the reviewer name is anonymised (the same for the author name for double-blind reviews). Do you think the rest of data about the review is also sensitive?

**Comment by Vitaliy-1** [comment]
example of data:
```json
{
      "id": 27,
      "isCurrentUserAssigned": false,
      "statusId": 0,
      "status": "Waiting for a response from the reviewer.",
      "dateDue": "2024-07-04",
      "dateResponseDue": "2024-07-04",
      "dateConfirmed": null,
      "dateCompleted": null,
      "dateAssigned": "2024-06-06",
      "round": 1,
      "roundId": 13,
      "recommendation": null,
      "dateCancelled": null,
      "reviewerFullName": "",
      "reviewMethod": 2
  }
```

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Alright, not sure whether someone would find these sensitive.

**Comment by asmecher** [comment]
@jardakotesovec and @Vitaliy-1, are there any critical elements here needing work before 3.5.0 can be released?

**Comment by jardakotesovec** [comment]
@asmecher All subitems are closed, so this can be closed as well.
