### ISSUE TITLE
[OMP] Usability testing results

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1127]
We role-played a complete publication process, using the latest `HEAD` of OMP, from initial author submission through to publication of a downloadable PDF. This is a list of problems and glitches we found.

I’m filing this one long issue, with the intention of filing separate, smaller issues as I get a better handle on them.

* author submission
 - [x] The initial submission form is intimidating. I believe that the form is the same as the one used for catalog information; it should be split apart, so the submission form can be separately configured per press preference. (Filed as #1143.)
 - [x] Can the initial submission form be configured, rather than changed through code? (Yes; it’s controlled by the Smarty template.)
* review (internal and external)
 - [x] It’s not obvious that review files have to be selected before the review process starts. A naïve user assumes that the submission files will be reviewed. (Filed as #1144.)
 - [x] Assigning a reviewer is confusing; it’s not immediately obvious that the Search By Name searches among the listed reviewers, and that the “Create New Reviewer” and “Enroll Existing User” links should be used. (And even then, which is appropriate? Unless the user has memorized the list of users, it’s hard to know. A more linear or wizard-ish workflow would help.) (Filed as #1146.)
 - [x] In the Enroll Existing User modal, it’s not obvious what the effect of the user group selection is, nor that the box populated with “Reviewer” is the place to type a name to search for. (Filed as #1147.)
 - [x] When a review is begun, the author is notified that their submission has changed status. However, the notification includes a link to the workflow (`.../index.php/workflow/access/4`), which the author does not have permission to see (“The current role does not have access to this operation”). (Filed as #1139.)
 - [x] A more useful notification typically follows on its heels. In fact, many notifications seem to be paired: “Hey, something happened,” and “Here’s useful information about what happened.” The less-informative notification could be suppressed. (Filed as #1148.)
 - [x] The notification e-mail to the reviewer still contains unfilled placeholders. (Covered by #1121.)
  ```
  Dear Christopher R. Maden,
 
 {$messageToReviewer}
  ```
 - [x] At some point, the system got itself in an odd state. User 2 is a member of group 18 (external reviewers). However, the user does not show up in the list of reviewers to select, but when attempting to add existing user as an external reviewer, the notification dialog spins indefinitely, and an error message is logged (filed as #1149):
  ```
  DB Error: Duplicate entry '18-2' for key 'user_user_groups_pkey', referer: .../index.php/test/workflow/index/2/5
  ```
* revisions
 - [x] There does not seem to be a way for the author to indicate that revisions are complete. They can upload files… but how does the editor know they’re done? (Filed as #1150.)
 - [x] Similarly, there’s no acknowledgment that the revisions have been received, until the editor actually accepts, declines, or sends the submission for additional review. (Filed as #1151.)
 - [x] The author was given the opportunity to replace (or update) one of the reviewer’s files during their revision upload. That seems inappropriate. (Filed as #1152.)
 - [x] The author uploaded a revision of their initial manuscript; however, the editor was unable to select the internal review revision file for subsequent external review, nor the external review revision file for copyediting. The file appears in the database, but is not presented as an option in “Upload/Select Files.” (Filed as #1153.)
 - [x] When the editor signs off on the submitted revisions, the message displayed is, “File Considered.” This is very unclear. (Filed as #1154.)
* copyedit
 - [x] As with revisions, there’s no evident way to signal that the copyedit is complete. The copyeditor can upload files, then stop uploading files, but there’s no “done” signal. (Included in #1150.)
* discussions
 - [x] When one user starts a Production Discussion, other users will see an odd, half-baked entry, until the first user finishes submitting it. It seems like the item should be invisible to other users until submission is complete. (Filed as #1155.)
* publication/catalog listing
 - [x] The process of actually listing an item in the catalog is confusing. The “Catalog Entry” link at the top is outside the workflow, visually, but each publication format needs to be added and approved within the Production tab. We’ve figured out the various things that need to be done, but the workflow is very nonlinear and never clear. (Filed as #1156.)
 - [x] In a catalog entry, an item without a cover image shows a “broken image” in the browser for its current cover. The system should be aware there is no image, and display something appropriate, rather than making users wonder. Also, multiple users attempt to click on the broken image in order to replace it, rather than using the file upload affordance beside it. (Filed as #1157.)
 - [x] At some point while editing the catalog entry, an error message was logged (filed as #1158):
  ```
  PHP Warning:  Illegal offset type in .../lib/pkp/classes/submission/SubmissionKeywordDAO.inc.php on line 57, referer: .../index.php/test/catalog/book/4
  ```

**Comment by asmecher** [comment]
Thanks, @crism. This will take a little while for us to run through, but I'll pass it by our UI/UX subgroup as a start.

**Comment by asmecher** [comment]
Thanks, @crism -- FYI we did talk about this briefly on our Monday meeting and were planning to split this into smaller issues for easier management, so thanks for getting the jump on us. Once I've swallowed the inbox shock this will be a valuable contribution.

**Comment by crism** [comment]
LOL @ inbox shock, @asmecher. Thanks for the replies you’ve already sent; I hope to be able to help address some of these.
