### ISSUE TITLE
[OJS] Update OJS frontend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1390]
There are a number of areas where the OJS frontend needs to be brough up-to-speed with some of the changes for OMP, as well as content that's still missing, particularly from article views.

- [x] Test existing settings for homepage content.
- [x] Test all default sidebar blocks
- [x] Search pages. #1667
- [x] Pagination (issue archives, announcements, search results)
- [x] Page titles in the head `<title>` tag should add the journal name after the page title name. SEO ftw!
- [x] Journals without thumbs on site index. https://github.com/pkp/pkp-lib/issues/1390#issuecomment-238014720
- [x] Style submissions checklist like OMP
- [x] Use multi-column layout with sections for article pages like OMP's book pages
- [x] Check galley display logic for issues and articles. See #1195  
- [x] Issue template missing footer. Caused by error in `access_legend.tpl`, which has been removed now as part of #1220.
- [x] ~~[Some content](https://github.com/pkp/pkp-lib/issues/1390#issuecomment-212396252) is missing on the frontend. See #1397 about possible consolidation.~~
- [x] Announcements aren't displayed on homepage
- [x] Announcements single pages lead to 404 -- Commit didn't make it into PR: https://github.com/NateWr/ojs/commit/ad3c7416f8392c008267aaed57667e53e16acfb9
- [x] Editorial Team link appears in nav menu even if masthead is empty.
- [x] Published date is entered in backend (Metadata > Publication) but not displayed on article page
- [x] Permissions data (Metadata > Publication) doesn't appear on article page. 
- [x] Look into overall site index with multi-journal setup. (Also, take a look at `$currentPress` usage in `primaryNavMenu.tpl`. Could rationalize menu display logic probably)
- [x] Overall site index has no primary nav menu. This disrupts the header. https://github.com/pkp/pkp-lib/issues/1508#issuecomment-223573579
- [x] Article page
 - [x] Article pages in issue
 - [x] DOI
 - [x] Other pub IDs
 - [x] Author ORCID https://orcid.org/trademark-and-id-display-guidelines
 - [x] Licensing should display copyright holder/date, _not_ journal copyright notice.
 - [x] Separate primary and supplementary files
 - [x] How to cite the item
 - [x] Article download stats
 - [ ] Article cover image. (It's missing from the forms in the backend. Will get solved as part of #1536.) 
- [ ] Issue Page
 - [ ] Display primary and supplementary files separately.
 - [x] Issue cover image
 - [x] PUblished date
- [x] Journal Index
 - [x] Homepage Image
 - [x] Announcements
 - [x] Latest Issue table of contents
 - [x] Arbitrary content block

**Comment by NateWr** [comment]
The following content doesn't appear to be displayed on the frontend:

- Settings > Journal > Masthead > Journal History
- Settings > Journal > Policies > Publication Scheduling
- Settings > Workflow > Production

**Comment by NateWr** [comment]
OJS PR: https://github.com/pkp/ojs/pull/827
(no pkp-lib PR needed)

This takes care of a number of issues. I thought it would be best to get them committed before the sprint. Still a bunch of things to work out.

**Comment by NateWr** [comment]
OJS PR: https://github.com/pkp/ojs/pull/833
(no pkp-lib PR needed)

Ticks off a few more issues, but still more to do.

**Comment by NateWr** [comment]
Ticked off a few more things in this issue:

https://github.com/pkp/ojs/pull/835
https://github.com/pkp/pkp-lib/pull/1442

**Comment by asmecher** [comment]
Merged those both, thanks!

**Comment by NateWr** [comment]
A PR for OMP with a couple of header-related changes made recently to OJS: https://github.com/pkp/omp/pull/285

A PR for the search bar borders in the head: https://github.com/pkp/ojs/pull/836

**Comment by asmecher** [comment]
(both merged)

**Comment by NateWr** [comment]
@asmecher I'm working through a little confusion around the copyright details. At the moment, it's easy for settings to indicate contradictory intentions: for instance the site setting may say "don't show license" but the article may have permissions data set. If a user has checked the attach permissions checkbox, they likely expect it to appear, unaware of the site-wide settings. 

I have a fairly lightweight proposal for an alternative. Here's a run-down of where things are now.

Under submission metadata, we have the following:

![selection_054](https://cloud.githubusercontent.com/assets/2306629/16304112/ea90d86c-394b-11e6-830a-f9338b182352.png)

Those fields are pre-populated from journal settings. If you don't check the box, the settings are not saved. But the actual setting, `attachPermissions`, is never saved to the article. It's [derived](https://github.com/pkp/ojs/blob/master/controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php#L159) from the status of the other data, and then some [JS workaround](https://github.com/pkp/ojs/blob/master/js/controllers/tab/issueEntry/form/IssueEntryPublicationMetadataFormHandler.js#L47) is in place to either check or un-check the box.

Separately, we have two global settings under Settings > Distribution > Permissions:

![selection_055](https://cloud.githubusercontent.com/assets/2306629/16304417/45249e02-394d-11e6-8b5e-165cbcb15fe1.png)

I'm running into trouble figuring out the precise logic to check against to determine when and how to display the copyright statement and license on article pages.

What do you think about removing the two options under Settings > Distribution > Permissions and the `attachPermissions` checkbox under article metadata. Then, I'd propose that the UI works like this:

- Default licensing details set up in Settings > Distribution > Permission (license URL, license owner, date)
- By default, the default licensing details are displayed uneditable in the article metadata form. An editor can toggle on a checkbox that says "Set custom permissions". When they do so, the fields can be edited and will be saved to article metadata.

The logic would work like this:

- When the form is saved, if the checkbox is checked, it will save data to the article. If not it will clear any permissions data in the article.
- The article accessor functions (eg - `getCopyrightHolder()`) would check for values in the article. If none are found it will automatically look up the journal settings.
- On the frontend, then, we can just check directly for the values from teh accessor functions. If they exist, we'll know they are intended to be displayed.

Does that sound like an approach that will satisfy our needs?

**Comment by asmecher** [comment]
On https://github.com/pkp/pkp-lib/issues/1390#issuecomment-228054917:

Copyright and license shouldn't be shown for the article unless someone (the editor) has seen them getting stamped on, so I'm not a fan of having the accessors go past the article to the journal settings.

The checkbox `attachPermissions` is useful so that we can show the editor what the permissions would look like based on journal settings, without implying that they're already attached to the article. We used to stamp these more automatically and got some pretty clear feedback on the process being too ambiguous.

**Comment by NateWr** [comment]
Ok, in that case, I think the display option checkboxes under Settings > Distribution > Permissions can probably go, since we want manual, article-by-article confirmation of display anyway.

Then it sounds like we're already kind of on the same approach I suggested, and on the frontend I can go straight to the article data without worrying about the global confic. The language and the global settings threw me off the path a bit. For the UI, I'd maybe just hide the licensing details when the box is un-checked and change the checkbox label to "Set license and copyright holder" or something like that.

**Comment by asmecher** [comment]
The licensing/copyright info is potentially presented in a lot of other places than just the reader front-end template -- via OAI, Google Scholar tags, etc. -- so the checkboxes (as currently intended) should only control whether they're shown on the reader interface in the template. The presence/absence of copyright/license data as entered on the form is a deeper concern.

Maybe this is the kind of thing best moved into a theme/template setting if one is needed, and I also wonder how many users will *not* want to present that data -- it's a legacy option we've always had but might not be justified. If you like, maybe we ought to take a stronger stance here and simply present the data whenever it's available, and remove those options from setup.

**Comment by NateWr** [comment]
@asmecher Ok, I've gone ahead and removed the global settings for displaying the copyright/license. It will always display when the data is attached to an article.

> The presence/absence of copyright/license data as entered on the form is a deeper concern.

My understanding is that when the `attachPermissions` checkbox is not checked, no license information is attached to an article. This is not displayed on the frontend and `Article::getLicenseUrl()` returns nothing.

![selection_001](https://cloud.githubusercontent.com/assets/2306629/16990802/5073f6a0-4e91-11e6-89a5-dcc7250d6d83.png)

Is that the deeper concern you're talking about? Should licensing data always be attached? Or should the form require licensing data?

I found when I tried to submit the form with all three fields empty (License URL, Copyright Holder, License Year) the form submits without error. However, only the Copyright Holder remains empty. The other License URL is re-filled with the default data from the global settings form, and the Copyright Year uses the current year.

**Comment by NateWr** [comment]
PRs to remove global copyright/license display settings:
https://github.com/pkp/pkp-lib/pull/1625
https://github.com/pkp/ojs/pull/937
https://github.com/pkp/omp/pull/308

**Comment by asmecher** [comment]
Thanks, merged the copyright/license PRs!

**Comment by asmecher** [comment]
From https://github.com/pkp/pkp-lib/issues/1390#issuecomment-233973039:
> My understanding is that when the `attachPermissions` checkbox is not checked, no license information is attached to an article. This is not displayed on the frontend and `Article::getLicenseUrl()` returns nothing.
> 
> Is that the deeper concern you're talking about? Should licensing data always be attached? Or should the form require licensing data?

The current behavior still seems logical to me, though it's entirely possible I'm missing the point... could you give me a scenario that you think we're not covering well?

**Comment by NateWr** [comment]
I'm not sure what "deeper concern" you were referring to in your previous comment. https://github.com/pkp/pkp-lib/issues/1390#issuecomment-228832306 My understanding is that it's possible for license details to not be attached to an article. All I'm asking is: is that a problem? Because I think it's possible.

**Comment by asmecher** [comment]
I was distinguishing between whether the license info is attached, and whether it is displayed. It's moot now that it's always displayed when available.

Yes, it's possible for license details to not be attached to an article. I don't think it's good practice, but we also need to support license information being attached whenever the appropriate editor is ready, so I think this is one of those cases where we can steer the editor but still allow them to shoot themselves in the foot.

**Comment by NateWr** [comment]
This PR adds the DOI and how-to-cite stuff to the article view page:
https://github.com/pkp/ojs/pull/938

No `pkp-lib` update required.

**Comment by NateWr** [comment]
This PR adds DOI, pub ID and cover images to issue summarys and table of contents views:
https://github.com/pkp/ojs/pull/940

**Comment by NateWr** [comment]
This PR does some minor adjustments to announcement display:
https://github.com/pkp/pkp-lib/pull/1633

This PR adds the latest issue to the homepage and improves display of announcements and homepage image:
https://github.com/pkp/ojs/pull/941

Although there's a `pkp-lib` PR here, the OJS PR is not dependent on it so I haven't included it as a submodule commit.

**Comment by asmecher** [comment]
All the above PRs are merged.

**Comment by NateWr** [comment]
Style adjustments needed for journals without a thumb on the site index.

![selection_021](https://cloud.githubusercontent.com/assets/2306629/17455972/3406617e-5bc0-11e6-921d-9e6b9c722e0a.png)

**Comment by NateWr** [comment]
PR with adjusted page titles:
https://github.com/pkp/pkp-lib/pull/1733

Waiting on tests here:
https://github.com/pkp/ojs/pull/976

**Comment by asmecher** [comment]
"Waiting on tests": I just got to that email notification now. Ah well :)
