### ISSUE TITLE
Multilingualism

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1807]
There are a few issues concerning multilingualism, that need attention, s. forum.pkp.sfu.ca/t/ojs3-and-multilingual-journals/19452/ and http://forum.pkp.sfu.ca/t/how-to-go-about-multilinugual-welcome-text-on-the-index-ojs-3-0/17002/5 and http://forum.pkp.sfu.ca/t/names-of-localizations-in-text-boxes-and-fields/21049
- [x] a) TinyMCE fields do not contain language designation, so that the user doesn't know where to write in which language. PR: https://github.com/pkp/pkp-lib/pull/2474
- [x] b) Some input fields (e.g. additional submission metadata fields like language and keywords) also do not have language designation. PR: https://github.com/pkp/pkp-lib/pull/2499
- <del>[ ] c) Is the logo upload meant to be like at the moment: to switch UI language in order to upload the logo in that language? -- Yes, currently it is so, till a multilingual file upload is not implemented/solved. </del>
- [x] d) First, the input field in the current UI language is displayed. This makes the required fields required for that UI locale (instead of submission locale) in the submission metadata form for editors. Solved here:https://github.com/pkp/pkp-lib/issues/2114
- [x] e) The author submission step 3 (metadata) fields are validated against journal primary locale and not submission locale. Solved here:https://github.com/pkp/pkp-lib/issues/2114
- [x] f) A strange effect: Lets say the submission locale is English and there is the submission title in English, primary locale and the UI language is German. When an editor opens submission metadata (UI = German), then cuts the English title and inserts it as German title (because it is marked as required, s. d) above), and then saves the form, the title will be saved as English title. Solved here:https://github.com/pkp/pkp-lib/issues/2114

**Comment by Ph-We** [comment]
Hi! I would also like to add Roles titles to this. Since those are displayed on pages and depend on language too. See here: http://forum.pkp.sfu.ca/t/ojs3-user-roles/23372

**Comment by asmecher** [comment]
@Ph-We, just glancing quickly over the code, role names should already be localized. Perhaps it's a minor bug rather than a missing feature?

**Comment by Ph-We** [comment]
@asmecher, thank you! Yes, now I've found what caused Roles not being localized. Sorry, my bad.

**Comment by asmecher** [comment]
@Ph-We, no problem!

**Comment by bozana** [comment]
I am not familiar with those issues i.e. do not know the solution immediately, thus either someone else does or could we defer it to 3.0.2?

**Comment by asmecher** [comment]
Agreed!

**Comment by Ph-We** [comment]
Hi @bozana, @asmecher,

The "Publisher" field (in the Masthead) is not multilingual. Is there any reason for this? 
It is important for it to be multilingual for journals to be indexed correctly.

**Comment by asmecher** [comment]
Hi @Ph-We -- see http://forum.pkp.sfu.ca/t/publisher-name-in-multilingual-journals/27557 for a discussion of this field.

**Comment by ajnyga** [comment]
Hi @bozana, especially issue a here is important for us since many of our journals are multilingual.
I am using this very simple approach to solve it: https://github.com/pkp/pkp-lib/compare/master...ajnyga:fix1807a?expand=1

That basically appends the name of the language before the tinymce box:
![screenshot_14](https://cloud.githubusercontent.com/assets/16347527/24003389/011ea5e0-0a6c-11e7-837c-b7b69142048d.png)

Below my code is an original code involving flag related css classes. Maybe that is an attempt to solve the same issue? But as you probably know using flags is not a good option.

**Comment by rkhalikov** [comment]
I'd like also to pay attention that for the following fields there is no possibility to add information in several languages:
1. Contact -> Mailing Address
2. Contact -> Principal Contact Name and Technical Support Contact Name (whereas Affiliation is multi language...)

**Comment by asmecher** [comment]
@NateWr, would you mind having a look at a) in the original entry and [@ajnyga's post and commit](https://github.com/pkp/pkp-lib/issues/1807#issuecomment-287089243)? It looks like the `:focus` selector doesn't work with TinyMCE elements, thus the language label on TinyMCE fields doesn't work. I think there's likely a CSS-only solution available but I'd be wasting everyone's time tinkering with it myself :)

**Comment by NateWr** [comment]
I chose to fix this in the template files themselves. It's basically the same as @ajnyga's fix.

![selection_199](https://cloud.githubusercontent.com/assets/2306629/25426283/8a53c8bc-2a66-11e7-838e-1a0f1b5d3de0.png)

PR:
https://github.com/pkp/pkp-lib/pull/2474

TESTS ONLY:
https://github.com/pkp/ojs/pull/1367

**Comment by bozana** [comment]
@NateWr, could you take a look at this PR: https://github.com/pkp/pkp-lib/pull/2499 ?

**Comment by NateWr** [comment]
Looks good @bozana. Would you take a look at my PR just above?

https://github.com/pkp/pkp-lib/issues/1807#issuecomment-297303569

Tests passed before (just one timeout), but I've rebased it again for clean merging.

**Comment by bozana** [comment]
@NateWr, it looks good :-) I just do not know if the tests failing is connected with the Travis issue @asmecher mentioned? -- I think so... Thus, do you think we can merge?

**Comment by bozana** [comment]
Hmmm... I will merge it now and then later run the major tests locally... and if there is a problem I will try to solve it...

**Comment by bozana** [comment]
Everything merged, thus closing...
