### ISSUE TITLE
Incorporate browse by section into core application

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2714]
## Updated (2019-07-18)
This issue description was updated to focus on integrating the [browseBySection](https://github.com/pkp/browseBySection) plugin into the core application, similar to how category browsing is part of the application.

## Original issue description
This will be especially popular for journals using a continuous publishing model.

- [x] Browse by section
- [x] Section-specific options for turning browsing-by on/off
- [x] Section descriptions
- [ ] ~~Options or Helper Functions for displaying last X articles from a section on the homepage~~ See https://github.com/pkp/pkp-lib/issues/4933 
- [ ] ~~Browse by subject/keyword~~ See  https://github.com/pkp/pkp-lib/issues/4932
- [ ] ~~Support faceting by Year/Issue/Volume~~ See preferred approach: https://github.com/pkp/pkp-lib/issues/4667

**Comment by NateWr** [comment]
@asmecher I've worked up browsing by section into it's own plugin, [browseBySection](https://github.com/NateWr/browseBySection) and put together [a PR with a few minor adjustments to OJS](https://github.com/pkp/ojs/pull/1641) to accomodate the plugin.

I'm not sure if a plugin is the best route for this. But I thought having some code would kickstart the conversation on how we want to do this. It would be pretty easy to work this into OJS `master` if that's where we wanted to house it.

As you may remember, I'm doing some pro-bono work for a journal that wants this feature and hopes to launch by end of November. If we don't get anything into `master` by then, that's fine, we can launch on the plugin. 

But it'd be nice to know if this implementation looks like what you were expecting or if you have any thoughts about the direction I've taken.

**Comment by NateWr** [comment]
Oh, I forgot to mention that one thing we'll need to address with this route is theme template overrides for plugins. Are you happy for me to work on this? 

I'm thinking just an extra path to check for loading templates from the active theme dir, so `/plugins/themes/templates/plugins/generic/browseByPath/` would map to `/plugins/generic/browseByPath/templates`. Does that sound good?

**Comment by asmecher** [comment]
I think generic plugins (etc.) should also be able to override built-in templates, but worry about the overhead of indiscriminately adding all plugin template paths. What about requiring plugins that want this behavior to call something in the `register` function to indicate that they should be added to the list?

**Comment by NateWr** [comment]
I was thinking that we'd only add the paths of the active theme and any of that theme's parent themes.

**Comment by NateWr** [comment]
Oh, sorry, I see there's been some confusion. I mean the ability for a theme to override a plugin's template. I'm not suggesting all plugins can overwrite templates.

**Comment by asmecher** [comment]
Yes, I'm just wondering whether that functionality might be useful to other plugin categories (particularly `generic`). Maybe that would mean moving `ThemePlugin::_registerTemplates` up to a parent class, but only using it within `ThemePlugin` -- that would allow other plugins to call to it if they wanted?

**Comment by NateWr** [comment]
Ah! Good thinking.

So, I have one slight concern about that. With a theme, we always have a hierarchy so we know which template receives priority -- active theme -> parent theme -> app -> pkp-lib. 

If we let any plugin override templates, we may encounter situations where we can't determine priority. For instance, maybe two author ID plugins both want to override a template to display their ID with the author details.

Template overrides are always one-or-the-other, so two plugins can't cooperate in modifying a template. For such situations, I feel like it would be better to make use of our hooks approach, which allows an unknown number of third-party plugins to inject content into a template without stepping on each other's toes.

Having said that, there may still be a case for allowing it as a possibility, but discouraging it's use as a regular practice.

**Comment by NateWr** [comment]
@asmecher I merged the changes to support a section plugin. Are you happy for it to be built as a plugin or would you like to see it in core? If you're happy with a plugin, I'll prepare the submodule commit too...

**Comment by asmecher** [comment]
Thanks, @NateWr. I don't have a strong opinion either way -- I guess a few questions play into it...
- How many users will want this? If a significant portion, better to build it in.
- Will different themes want to interact with this functionality? If so, better to build it in.
- Are themes likely to implement alternative options? If so, better to leave it a plugin.

**Comment by NateWr** [comment]
I think...

> How many users will want this?

Probably mostly just the continuous publishing model crowd. Though there will be some others who might want it.

> Will different themes want to interact with this functionality?

If we support plugin template overrides, I think it won't matter whether it's a plugin or built-in.

> Are themes likely to implement alternative options?

I'd like to see themes stick to presentational matters, and keep "functionality" in separate plugins. Themes have really combined the two in the WP ecosystem and it's a nightmare. Over the long term, sites get locked into a theme if too much of their functionality comes from the theme, because they can't easily jump from one theme to another.

**Comment by asmecher** [comment]
Yep, that makes sense to me.

Is there a repo/PR with the code open? I don't see anything linked here.

**Comment by NateWr** [comment]
I haven't yet done any frontend styling, but it's all working fine off of this plugin, which I've just transferred to PKP control: https://github.com/pkp/browseBySection

If/when you're happy with the implementation, I can work up support in the default/manuscript/bootstrap themes.

**Comment by NateWr** [comment]
Ok, I addressed some of the comments on your code review. Unless you think otherwise, I'm going to work on a service class for published items as part of #1922.

In addition to the plugin, there's one change that's needed in pkp-lib.

PR:
https://github.com/pkp/pkp-lib/pull/3118

**Comment by NateWr** [comment]
@mfelczak do you know which part of this issue is the sponsored development scheduled for 3.2?
