### ISSUE TITLE
Refactor backend UI to improve accessibility and use Vue.js

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5865]
This issue describes work on the editorial and administrative backend that provides a new page architecture driven by Vue.js. A short summary of this work includes:

- Adds new page layout that increases focus on main content and removes the main navigation menu for users with only one navigation item. (See [screenshots](https://github.com/pkp/pkp-lib/issues/5865#issuecomment-628070632)).
- Migrates navigation menus and header dropdowns to Vue.js. (See [screenshots](https://github.com/pkp/pkp-lib/issues/5865#issuecomment-628071663)).
- Refactors `ListPanel` components to use slots in order to be easier to build and extend.
- Adds Vue.js support for modals and dialogues (#3595)
- Adds technique for accessing global constants, locale strings and CSRF token in Vue.js (#4639, #4379)
- Replaces announcements grid with new list panel. (#4081)
- Replaces PNotify with own toast-style notifications. (See [screenshots](https://github.com/pkp/pkp-lib/issues/5865#issuecomment-628072332)).
- UI Library documentation restructured to document utilities and pages.
- Restores ability to open to a tab with an #anchor. Use `#parent-tab/child-tab` to reach nested tabs.
- Removes Underscore.js dependency.
- Uses more accessible technique to broadcast when forms are saved and saving. (See [screenshots](https://github.com/pkp/pkp-lib/issues/5865#issuecomment-628072944)).
- `<pkp-button>` components use slots.

This work is not yet ready for merge. When it is clear to merge in 3.3, the following work needs to be done.

- [x] Migrate changes to OPS.
- [x] Add a database migration to change the announcements `expiryDate` from `DATETIME` to `DATE`.
- [x] Refactor select list panels in #5694.
  - [x] OMP appears to have a category list panel in its SeriesForm that needs to be fixed.
- [x] Refactor select reviewer list panel to use new FilterSlider. #5601
- [ ] Refactor scheduling in issue workflow to use one modal, a clearer set of steps, and a cancel button. #5532 

PRs (not ready for merge):
https://github.com/pkp/ui-library/pull/88
https://github.com/pkp/pkp-lib/pull/5866
https://github.com/pkp/ojs/pull/2746
https://github.com/pkp/omp/pull/812
https://github.com/pkp/ops/pull/38
https://github.com/pkp/quickSubmit/pull/48
https://github.com/pkp/citationStyleLanguage/pull/71

Additional work that would be nice to include if time permits:

- [ ] The main navigation menu should be sticky if it is not too tall for the browser window.
- [ ] Several basic components, such as `<badge>` and `<pkp-button>` have been made global components. More components could be made global so that they can be used by plugins.
- [ ] Support browser history in tabs (#2773)

**Comment by NateWr** [comment]
A new page layout that provides more breathing space.
![page-layout](https://user-images.githubusercontent.com/2306629/81833106-36010d80-9537-11ea-8acf-b2ed07d727bc.png)

Users that have only one navigation item (authors, reviewers, section editors, subscription managers) don't see a navigation menu.
![author-view](https://user-images.githubusercontent.com/2306629/81833200-55983600-9537-11ea-9795-a9d41871be39.png)

When not on their "home" page (submissions or payments), they get a link back to it in the header.
![author-workflow](https://user-images.githubusercontent.com/2306629/81833269-6ba5f680-9537-11ea-9eeb-4b2a8db5cd17.png)

**Comment by NateWr** [comment]
The user nav has been tidied up.
![user-nav](https://user-images.githubusercontent.com/2306629/81833482-af98fb80-9537-11ea-9e4a-921731f1b5cb.png)

And includes a clear indication when logged in as another user.
![user-nav-logged-in-as](https://user-images.githubusercontent.com/2306629/81833513-b9bafa00-9537-11ea-8479-279a0aa9bf65.png)

**Comment by NateWr** [comment]
New toast-style notifications.
![toast-notifications](https://user-images.githubusercontent.com/2306629/81833672-e838d500-9537-11ea-8027-7f6afb7d2e05.gif)

**Comment by NateWr** [comment]
Forms now broadcast their Saving/Saved status messages in a more accessible way.
![save-form](https://user-images.githubusercontent.com/2306629/81833797-0dc5de80-9538-11ea-904f-8341de981fb7.gif)

**Comment by alexxxmendonca** [comment]
This all looks so beautiful 😍
👍 👍 👍 👍

**Comment by asmecher** [comment]
Jeez, @NateWr, I'm practically blind to the UI I'm working with when I get so used to it -- but when improvements like these are proposed they seem so obvious in hindsight. :100:

**Comment by NateWr** [comment]
An error during rebase led to a fatal error with announcements. The PR below fixes that and adds a test to catch further regressions.

PR:
https://github.com/pkp/pkp-lib/pull/6034

Tests:
https://github.com/pkp/ojs/pull/2820

**Comment by asmecher** [comment]
@NateWr, I think this broke the Travis tests for OMP master. The log fills with:
```
PHP Warning:  Illegal string offset 'id' in /home/travis/build/pkp/omp/controllers/grid/users/chapter/form/ChapterForm.inc.php on line 151
```
...until Travis kills the job because of log length.

**Comment by NateWr** [comment]
I think I fixed it in the commit above, but I can't actually find a build of OMP reflecting that. Is there a way in Travis to kick off a test on the latest master branch, short of raising a PR on it?

**Comment by willinsky** [comment]
Let me leave my compliments, as well, Nate, for the clean, informative, tasteful UI design. 

On this one design below, I wondered about the way that the article title lacks the white framing background and just sits in the background. I'd suggest keeping the pattern from the submissions list of author in bold over the title only set it in its own narrowly framed box of white (or very light gray) background. I wouldn't line it up with "Library" as it suggests some connection. There is no "Help" tab in this one, which I wasn't sure about but Library is in more of that category, as a resource, and could be placed either where Help goes or near Help if Help is to be added.

<img width="1504" alt="Screen Shot 2020-07-02 at 2 44 52 PM" src="https://user-images.githubusercontent.com/10342108/86413199-78acaf80-bc75-11ea-9f17-7e0285a8606d.png">

**Comment by NateWr** [comment]
OMP was missing some of the new code for announcements.

PR:
https://github.com/pkp/omp/pull/846

**Comment by NateWr** [comment]
The OMP master branch should be fixed now.
