### ISSUE TITLE
[UI] Grid components

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#601]
The following are outstanding issues in the [new UI fork](https://github.com/NateWr/pkp-lib/tree/header_ui) related to grid compoments.

**Broken Functionality**
- [x] Infinite scrolling is now broken. See #656 
- [x] Settings > Website > Plugins: Plugin-specific links (when row opened) won't go anywhere. LEad to 404 erorr in apache log
- [x] Settings > Website > Plugins: expand/collapse doens't do anything because they're always expanded. (I think it's best to be always expanded here so maybe remove the expand/collapse links)
- [x] Dashboard > Submissions: submissions loaded via the infiinite scrolling feature do not appear to have action rows. Maybe related to #576
- [x] File IDs in grids don't appear. Maybe that's just not been merged with master yet? See [PR#644](https://github.com/pkp/pkp-lib/pull/644)

**Needs Styling/Markup Adjustments**
- [x] Grids in administration screens need styling. See #665 
- [x] Files in grids used to get classes assigned to their link element of `sprite pdf` which indicated the file type (`sprite image`). But now that's not happening, so the file type icons can't be shown. Need to get those back in.
- [x] After each file in a grid there's an empty <a> that is a link to the notes. It used to turn the correct color depending on if there are new notes or not `Notes (yellow: has new notes; blue: has viewed notes; grey: no notes)`. That's no longer appearing and I don't get useful data on whether it's new or not because I stripped that part out of the link action. Woops. Needs to be added back in, probably just as a class (or two) attached to the file link.
- [x] Settings > Users > Users > Search drop down styling
- [x] Settings > Users > Roles >: Search drop down styling
- [x] Can't delete user roles. See #666
- [x] The type to create new item control in: : `Settings > Workflow > Review > Review Form Item > Form Items > Create New Item > Response` `Settings > Users > Role > Create Role`
- [x] Submission > Review > Add Reviewer > Advanced Search: Search form needs to be styled.

**Accessibility**
- [ ] Ordering grids is not accessible to keyboard users. #1671
- [ ] ~~Actions inline with the main grid row are not focusable. (Footer links is only place I know if it now. It's items in `.row-actions`)~~

**MOAR GRIDS** (needs styling adjustments)
- [x] Add reviewer > Review files
- [x] Copyediting > Discussions > Select Files > Show all files

**Future**
- [x] Instead of embedding a grid help description into the top of the grid, it should have a help icon which opens a help panel with that text. A pattern for this is set out in my [NateWr/pkp-admin-sketches](https://github.com/NateWr/pkp-admin-sketches/), but requires a bit of heavy lifting to get there.

**Comment by asmecher** [comment]
Likewise, have a look to see what's current, @NateWr?

**Comment by NateWr** [comment]
Only one outstanding issue related to keyboard accessibility. I filed a separate issue pegged to OJS 3.0.1 for that. Closing.
