### ISSUE TITLE
[UI] Form components

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#602]
The following are outstanding issues in the [new UI fork](https://github.com/NateWr/pkp-lib/tree/header_ui) related to form compoments.

The form components underwent the least revisions and are largely in place as they were. However, there are still a number of changes that require improvements to styling. In the long-term, the markup needs substantial revision for accessibility as well as just using proper markup. There's some oddities in there.

**Broken/Unusable Functionality**
- [x] All Tag-It form components need styling. See [PR#646](https://github.com/pkp/pkp-lib/pull/646)
- [x] Submission metadata doesn't save. See #667.
- [x] Datepicker unstyled. See `Settings > Website > Announcements > Add Announcement > Expiry date` See [PR 645](https://github.com/pkp/pkp-lib/pull/645)
- [x] Submission > Review > Add Reviewer: Input field is to start typing, then get a list of matches. This needs to be styled. See [PR 647](https://github.com/pkp/pkp-lib/pull/647)

**Needs Styling**
- [x] Save/cancel buttons in ajax forms are not aligned well in general.
- [x] Submission > Metadata modal. Buttons row is not aligned properly. Markup needs a close look.
- [x] Settings > Journal > Sections > Create Section: form alignment issues with the bottom buttons
- [x] TinyMCE would really benefit from some better style defaults in its text editor. Looks like we're just loading a vendor file at the moment. #990
- [x] When making a submission, on the Enter Metadata stage, there is a link for "Extended Metadata". It's not terribly clear this will open up more details. Could use some improved styling.

**Improvements**
- [x] The * Required Field text at the bottom of some forms is not well aligned or marked. Probably need to rethink location.
- Tag-It component autocomplete sends a query to a 404 (test in Submission > Metadata). Seems to work elsewhere, like Review Interests in user profiles). (Re-filed here for OJS 3.0: https://github.com/pkp/pkp-lib/issues/673 - AS)

**Accessibility**
- [ ] Check out aria-labelledby and aria-describedby for compositing descriptions of fields from more than one location. This will be useful if we get to refactor the form builder vocabulary system.
- [ ] Only one label per field.
- [ ] Use fieldsets for radio button groups

**Comment by asmecher** [comment]
@NateWr, likewise, could you look this one over?

**Comment by NateWr** [comment]
The remaining issues are things that would need to be sorted in a broader refactor of the FBV. Closing.
