### ISSUE TITLE
[UI] Modal components

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#603]
The following are outstanding issues in the [new UI fork](https://github.com/NateWr/pkp-lib/tree/header_ui) related to modal compoments.

Modals underwent the most significant revision. They no longer use the jQuery UI dialog widget, which required a bit of realigning of events and things. A few handlers still have not been properly worked through. Several of these issues appear in the UIUX demo install, though, so are probably problems that pre-date the UI overhaul.

**Handlers Not Yet Tested/Revised**
- [x] AjaxLegacyPluginModalHandler (custom block manager plugin)
- [ ] JsEventConfirmationModalHandler (used in user grid row)
- [ ] WizardModalHandler (how can I start the wizard up to test?)

**Broken/Unusable Functionality**
- [x] Submission > Add Participant. The save button never "completes" and closes the modal, and no notification is popped up. But the participant does get added once the page is refreshed.
- [x] Submission > Add Participant. When the participants modal closes, focus is put back on the partcipants fly-out, but it's positioned off-screen so the tab container gets shifted partially out of view
- [x] Submission > Expedite Submission. Clicking OK doesn't do anything. RemoteActionConfirmationModalHandler.js::remoteResponse() receives json content which seems to be an HTML representation of the IssueEntryMetadata controller. But this is not displayed in any way by RemoteActionConfirmationModalHandler and the submission never gets expedited. I suspect it's supposed to load up the metadata modal for entry as a next step towards expediting?
- [x] Settings > Workflow > Components: Restore Defaults doesn't work
- [ ] ~~Settings > Website > Announcements > Add Announcement: saves but the modal never closes and the spinner is still there.~~ https://github.com/pkp/pkp-lib/issues/1673
- [x] User Import/Export: Export all users doesn't work
- [x] RemoteAction: Dashboard > Issues > Future Issues: Publish Issue. Redirects to non-existant URL. IssueGridHandler.inc:406 and IssueGridHandler.inc:437 are the bad redirect routes.
- [x] RemoteAction: Dashboard > Issues > Future Issues > Edit > Issue Galleys. Try to delete a galley and an error message that says "Invalid issue requested" appears. See [PR#570](https://github.com/pkp/ojs/pull/570)
- [x] RemoteAction: Dashboard > My Assigned > Delete Submission: When I delete, it doesn't update the grid. When I reload the page the whole grid hangs during loading. I get nothing in my error log, but the grid no longer loads due to some phantom error. I have to dump and reinstall the demo database to get it working. Looking into the specific ajax hanging problem, I found that when the RemoteAction modal response is received after deleting a submission, it fires the dataChanged event. This is processed by the grid to update itself. It appears that GridHandler.js::refreshGridHandler() is firing the request, but nothing is received back. This is probably a result of the same phantom error that's causing the grid to no longer load after this action is processed.
- [x] Submission > Review > New Review Round: Loading spinner appears  in modal (without spinner) See #679 
- [x] Submission > Review > New Review Round: Clicking ok button ("create new round") leads to full page load of json response (but review round is actually created). JSON:  `{"status":true,"content":"","elementId":"0","event":{"name":"redirectRequested","data":"http:\/\/localhost\/ojs\/index.php\/publicknowledge\/workflow\/externalReview\/2"}}` See #679 
  p\/publicknowledge\/workflow\/externalReview\/2"}}` See #679 
- [x] Submission > Review > Review Files. Add a new file. When the modal closes, the list of files isn't refreshed.
- [ ] Submission > Review > Review Files: Click "Include all files from previous stages". A file appears. Click More Information for that file. When the modal is closed the file has disappeared. The same is true fro Submission > Editorial > Upload/Select Files. Editing the metadata there doesn't save anything, and it throws an error in the console when opening the modal.
- [x] Submission > Review > Add Reviewer: Modal saving stalls and reviewer is not added.
- [x] Submission > Editorial > Assign Auditor: Saves but modal stalls out.
- [x] Submission > Production > Galley Files > Manage Dependent Files: Modal ajax content never loads (Is this gone now? I couldn't find this.)
- [x] Submission > Production > Galley Files > View Document Library: ajax load error. 404 at `http://localhost/ojs/index.php/publicknowledge/$$$call$$$/grid/files/galley/galley-files-grid/view-library?submissionId=5&stageId=5&fileStage=10&representationId=12&assocType=521&assocId=12&_=1439390978469`
- [x] Submission > Production > Galley Files > Approve Proof: Once approved, the link text doesn't change. So it says "Approve Proof", but when you click on it it asks if you want to disapprove proof. Fixed in [NateWr/pkp-lib/d4a38b4d](https://github.com/NateWr/pkp-lib/commit/d4a38b4d1654d52cbdf4ae03928cd6d2237a9214)
- [x] New submission process: step 3 gets the [email error](https://github.com/pkp/pkp-lib/issues/600), does not forward to next step

**Needs Styling**
- [x] Submission > Editorial History > Notes. Notes are unstyled and when a note is added the spinner never disappears.
- [x] Notifications sit over the top of the close button (X in corner) (see future issue on notifications now missing pin/close icons)
- [x] Issue covers

**Improvements**
- [x] Modal button positions should be standardized. Right now my confirmation modal buttons are `OK` on left with `Cancel` beside, but the forms have `Save` on right with `Cancel` on left. Implement a pattern that works for both (including the spinner).
- [ ] RedirectConfirmationModalHandler shouldn't really need to exist. The LinkAction should just use the `href` attribute of the link element and the ButtonConfirmationModalHandler should just click through the link once confirmed. Doing this turned out to be a deep, deep rabbit hole.

**Accessibility**
- [ ] Use hidden elements at the top and bottom of the modal which can "trap" the focus. When you reach the top element, push focus to the bottom element. Maybe also include top and bottom elements with screen reader text which alert the user about this action and allow them to close the modal.

**Cleanup**
- [ ] Look at DEFAULT_OPTIONS in ModalHandler.js. Several are no longer needed since moving away from the jQuery UI dialog element, but should be also removed from other places, like when the handler is instantiated in link actions or .tpl files

**Comment by NateWr** [comment]
I've updated the status for several things. The remaining bits are very low priority. I'll move to OJS 3.0.1, but we may want to consider which of the remaining issues we want to spin off for later.

**Comment by asmecher** [comment]
@NateWr, any firm priorities for 3.1?

**Comment by NateWr** [comment]
Closing as obsolete.
