### ISSUE TITLE
[UI] Header/Tasks/Site-wide issues

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#605]
The following are outstanding issues in the [new UI fork](https://github.com/NateWr/pkp-lib/tree/header_ui) related to the header, tasks or general site-wide aspects of the backend.

**Sidebar**
- [x] The sidebar is still getting printed into the markup of the editorial backend pages. It's just being hidden by CSS for now, but it should get removed completely. Fixed in https://github.com/NateWr/pkp-lib/commit/3a6c3ea0f2d6e147bebfc9bee69c99e6f4800537

**Header**
- [x] Page logo is missing in admin areas (no site context).
- [ ] Make skip-to-content screen reader links work by adding a dummy anchor element or making the sections focusable and shifting focus there.
- [x] HeaderHandler.js is now only covering the help on/off, which is only currently a link in the frontend. Maybe this can go away completely at some point.
- [ ] updateHeader js event is called several times, but no longer has meaning in the backend.<sup>[1](#updateHeader)</sup>

**Navigation Menus**
- [x] Fly-out menus can go off-screen. Need to add a bit of JS to the handler to adjust their position if necessary.
- [x] Site switching in multi-journal context sends people to the frontend, but it should probably send people to the dashboard or, better yet, the same page they're on, just on a  different journal (ie - settings, dashboard, etc).
- [x] When not in a journal context, the site switcher still lists "select a site" as an option. Need to track that down and squash it.
- [x] Backend navigation needs a link to user profile.

**Tasks Panel**
- [x] Currently it uses `<strong>` to mark up read/un-read. Need to use class on row wrapper for better styling possibilities.

**Notifications**
- [x] The notifications windows have little pin and X elements that are no longer being displayed. Should just need to attach some icons via CSS. See [PR#651](https://github.com/pkp/pkp-lib/pull/651).
- [ ] The notification close button often takes several clicks to actually close. I suspect maybe some race conditions of some kind, but not sure.

**Notes**
<a name="updateHeader">1.</a> For several forms (example: Settings > Website > Appearance), on submission it triggers a js event `updateHeader`, which calls and refreshes the header handler.

But on the backend we no longer have a header handler as such. We have a tasks handler and a user nav handler.

Right now we sort of don't completely break down because the code finds the header handler by searching for `#navigationUserWrapper`, and passing the handler attached to that element.

This is super fragile and we'll need to either abandon the refresh for these forms or look at them one-by-one and see what we need to refresh.

The same is true for a `updateSidebar` event, though we'll evaluate when we get to the frontend.

**Comment by NateWr** [comment]
Re-assigning this to OJS 3.0.1.

**Comment by asmecher** [comment]
@NateWr, any firm priorities for 3.1?

**Comment by NateWr** [comment]
Closing as obsolete.
