### ISSUE TITLE
CrossRef and DOI UI/UX quality of life improvements

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#6062]
Outline of changes to be made to the CrossRef and DOI plugins to improve the usability of the CrossRef plugin and DOI management workflows.

DOI Tasks
- [x] Restrict the availability of custom DOI suffixes
- [x] Remove "nuclear button" options to clear and/or reassign DOIs from web GUI
- [x] Provide a direct link to the DOI management page in Dashboard for managers
- [x] Remove  DOI management functions that have been scattered throughout the OxS UI

CrossRef Tasks
- [x] Update DOI management to use new Vue.js display UI
- [x] Add a "Select all" button
- [x] Add an Issues filter
- [x] Add DOI status filters
- [x] Provide straightforward actions for selected DOIs (e.g. batch reset or clear DOIs, check status, etc.)
- [x] Improve DOI submission error feedback

**Comment by ewhanson** [comment]
Hi @NateWr and @asmecher, thanks for your initial feedback and for taking a look at the work so far. I prepared draft pull requests for OJS, pkp-lib, and the UI library.

Thanks!

PRs:
pkp/ojs#2949
pkp/ui-library#134
#6466

**Comment by NateWr** [comment]
Looks good, Erik! I haven't looked at the code, but here are a few suggestions for the UI/UX.

1. Move the menu item to the top group and call it "DOIs". This should be treated like content that is managed regularly rather than settings.
2. "Article DOI Management" -> "Article DOIs" (same with issues)
3. Convert the issue select filter to `FieldSelectIssues` (plural -- see the submission lists)
4. The ListPanel needs support for pagination.
5. "Not Published" -> "Unpublished"
6. "! Needs Depositing" -> "Not Deposited"
7. We can't use a `<list-item>`'s value slot for text like that, because it has a fixed width and the width of text will change from language to language. Try using a [Table](http://localhost:8080/#/component/Table/with-custom-column) with a custom column for the field. There may be accessibility issues with that which need to be investigated. The `Table` component is a DataGrid but we may need to look more closely at how to implement [editable cells](https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html#ex2_label)... or consider an alternative. Maybe even turning the whole bottom bit into a `Form` to meet accessibility requirements.
8. The crossref deposit string (`notDeposited`). This should be at the DOI level, rather than the submission level, right? Wouldn't each DOI have its own status?
9. I'm seeing `settingValue null` in the console when I click Edit on a DOI.

The most common action here will be to go in and deposit all outstanding DOIs, right? I'm always nervous about Select All features because those only work for the items in the list, but users don't always clearly understand that there may be additional items in other pages that are not included in the action. We also can end up with submissions falling through pagination gaps as they select all in one page, deposit, go to the next page and repeat. In the time between depositing one page, and loading the next page, the count can change, so that a submission moved from page 2 to page 1. That submission will not get deposited because the user thinks they've already done everything on page 1.

If we think the most common desired action is to deposit all outstanding DOIs, let's make an action that does that. Here's an example of how that can work:

![deposit-dois](https://user-images.githubusercontent.com/2306629/102342871-c736d780-3f91-11eb-8034-96e33b489846.gif)

In terms of the design/layout, I think we're in danger of having too much button clutter at the top. Here are some ideas to consolidate controls and reduce cognitive load.

Consider moving the select/actions stuff into a single control. The way that it is done now, the Actions don't appear to be related to the Selected items. Here's what that might look like:

![bulk-actions](https://user-images.githubusercontent.com/2306629/102343228-2dbbf580-3f92-11eb-82ae-3903f5285cb5.png)

And lastly, there's always an option to show filters by default. This can reduce the number of buttons at the top. And my guess is that managers will rarely want to use the default view. They'll want to be looking for published submissions or filter by issues.

![sidebar-visible](https://user-images.githubusercontent.com/2306629/102343376-5e9c2a80-3f92-11eb-8ef1-9516afe5eca1.png)

**Comment by NateWr** [comment]
I forgot to add that you can see the hacking I did for these suggestions at https://github.com/NateWr/ui-library/commit/d6c0273ab8e9a26722516b7d5599aa288c17f2d5

**Comment by NateWr** [comment]
Sorry, I also forgot my recommendations for the expanded item area. The actions should be moved down below the list. This will also keep it from cluttering the summary with badges/buttons.

![doi-single](https://user-images.githubusercontent.com/2306629/102344394-bdae6f00-3f93-11eb-8cb9-51cce9485041.png)

**Comment by NateWr** [comment]
Last one, I swear! I notice that the list includes incomplete submissions. These can probably be removed (pass a false `isIncomplete` param in the `getParams`). You might even consider removing everything that's not in Copyediting/Production -- though check with James/Mike first.

**Comment by ewhanson** [comment]
Thanks, @NateWr! This all sounds great and is really helpful. I'll work on getting this implemented and ping you once it's done.

**Comment by bozana** [comment]
Hi @ewhanson, I have taken a look into the code and everything looks very good for me (a lot of things are also new for me, but as far as I could see it for now...). Great work! :star: 
I have only two questions:
It is checked if the Crossref plugin is enabled in order to add/provide the Crossref functions, right? I think the import/export plugins are enabled per default, so maybe it could be checked if the required Crossref plugin settings are there, e.g. depositor name, instead? (I actually suppose that all this and some fine tuning will come when the Crossref deposit function is integrated and/or with some of those TODOs left in the code... but wanted to double check and keep in mind...)
Could there maybe be a way to consider changing/editing/assigning a DOI to different article versions? -- Currently only the last published version is considered in the new DOI Management page. As far as I understand this is the main way that we would like to support, but -- as currently possible in the identifier tab -- we allow the editor to assign different DOIs to different versions/publications, but leave also the responsibility to him/her to register it correctly/manually. Would this kind of support be possible in the new DOI Management page as well?
Thanks a lot!

**Comment by ewhanson** [comment]
Hi @NateWr, I've gone through and updated the UI aspects of the the DOI Management page based on your feedback. Would you be able to have a look. Here are a few notes on the changes. Thanks!

- As you suggested, I replaced using the `<list-item>`’s value slot with a `Table`.  With it set as a table, the column size is changing when interacting with it. Do you have any recommendations on how to handle this?
![2021-03-28 19 43 46](https://user-images.githubusercontent.com/20844845/112781110-0ea41980-8fff-11eb-893f-e3dd0292389d.gif)
- You asked about `notDeposited` and how it’s currently at the submission level rather than the DOI level. The data is sent to Crossref at a submission level, so the status will be the same for all DOIs associated with a submission. 
- Regarding which submission to include on the DOI management page, I talked with Mike about this, and his perspective was that only published articles should be showing up here. I’m not sure if this would conflict with some of the potential use cases, so I’ll hold off on making that change for now. 

The drafts PRs are the same as before.

PRs:
pkp/ojs#2949
pkp/ui-library#134
#6466

**Comment by ewhanson** [comment]
> Hi @ewhanson, I have taken a look into the code and everything looks very good for me (a lot of things are also new for me, but as far as I could see it for now...). Great work! ⭐
> I have only two questions:
> It is checked if the Crossref plugin is enabled in order to add/provide the Crossref functions, right? I think the import/export plugins are enabled per default, so maybe it could be checked if the required Crossref plugin settings are there, e.g. depositor name, instead? (I actually suppose that all this and some fine tuning will come when the Crossref deposit function is integrated and/or with some of those TODOs left in the code... but wanted to double check and keep in mind...)
> Could there maybe be a way to consider changing/editing/assigning a DOI to different article versions? -- Currently only the last published version is considered in the new DOI Management page. As far as I understand this is the main way that we would like to support, but -- as currently possible in the identifier tab -- we allow the editor to assign different DOIs to different versions/publications, but leave also the responsibility to him/her to register it correctly/manually. Would this kind of support be possible/make sense in the new DOI Management page as well?
> Thanks a lot!

Hi @bozana, thanks so much for the feedback! And sorry for taking so long to get back to it.

For your first question, right now the import/export plugins are not loaded by default, only the generic and pubId plugins are (hence the messy work around). This came up before in #5467, which resulted the pubId plugins being loaded from the beginning alongside the generic ones. One solution that we talked about before would be to create a generic plugin wrapper around the current Crossref import/export plugin so that it would be loaded at the beginning. What are your thought on that idea?

Regarding assigning DOIs to different versions of the article, based on feedback from Mike Nason, the goal right now is to remove the ability for editors to assign different DOIs to different versions (this will be removed from the identifiers tab). Based on the workflow Mike outlined to me, when a new version of a publication is created, the metadata (including information about the update) should be pushed to Crossref to update the existing DOI. I don’t think adding this in to OJS specifically makes sense quite yet, but this type of functionality will be necessary if the new DOI Management page is going to be used with OPS in the future. 

How does all that sound to you?

**Comment by NateWr** [comment]
> based on feedback from Mike Nason, the goal right now is to remove the ability for editors to assign different DOIs to different versions

I'm sympathetic to @AhemNason's position, but at the Barcelona sprint it was clear that there is not agreement on this point (cc @mtub). Some institutions will want/expect to be able to assign a different DOI to different versions. The current DOI assignment UI was designed to discourage but permit this.

I'll keep this in mind during my review and see if there is some way that we can work this into the new UI, while still discouraging it as a normal practice.

**Comment by ewhanson** [comment]
Thanks for the context @NateWr. That's helpful to know. I'll take a look at adding that for the export/depositing side of things.

**Comment by AhemNason** [comment]
It wasn't just my opinion. It was Crossref's.

**Comment by AhemNason** [comment]
Multiple versions of pre-prints is recommended. Using Crossmark for DOIs for published articles is recommended.

**Comment by ewhanson** [comment]
Hey @asmecher and @NateWr, I'm working on setting up an API call for handling the exporting/depositing actions for the Crossref plugin and ran into an issue. I'm using a custom API endpoint to trigger the exporting/depositing logic from `CrossRefExportPlugin` but run into trouble in the filter here: https://github.com/pkp/crossref-ojs/blob/bf4d17d6c4bd7de8b25916c49e75617599e39af1/filter/IssueCrossrefXmlFilter.inc.php#L194-L197
```php
if ($issue->getDatePublished() && $issue->getStoredPubId('doi')) {
	$request = Application::get()->getRequest();
	$journalIssueNode->appendChild($this->createDOIDataNode($doc, $issue->getStoredPubId('doi'), $request->url($context->getPath(), 'issue', 'view', $issue->getBestIssueId($context), null, null, true)));
}
```

The request in this case is coming from the `APIRouter` and I'm getting this exception: "APIRouter::url() should not be called with an op, path or anchor. If a new context is passed, the context path must be passed instead of the context object."

Any advice on how to approach handling this from within an API call or starting a new request to handle the exporting/depositing?

Thanks!

**Comment by asmecher** [comment]
@ewhanson, OJS picks a router if you don't specify one, and in this case it picked the API router when you actually want to generate a page router URL. You can manually specify what kind of router you need as follows:
```
$dispatcher = $request->getDispatcher();
$url = $dispatcher->url($request, ROUTE_PAGE, $context->getPath(), ...)
```

**Comment by ewhanson** [comment]
Thanks @asmecher, that's exactly what I was looking for!

**Comment by fgnievinski** [comment]
I'd like to suggest splitting in three the current option of the CrossRef plugin to enable DOI for (all) galleys:
a) enable DOI for supplementary materials
b) enable DOI for article main body file formats
c) enable DOI for article main body items (tables, figures)

Option (a) is more common in commercial publishing, where additional DOIs would be registered for supplementary materials (meaning appendices to the article main body) only if they are expected to be specifically linked to from the article main body. Examples are additional tables or figures or a detailed methods section to large for the main body. Supplementary materials are special also because sometimes they are indexed for citation analysis ("Use and mis-use of supplementary material in science publications"[[1]](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0668-z)).

Option (b) could be disabled by default. We shouldn't be encouraging the assignment of additional DOIs for each file format (PDF, HTML, XML) of the article main body (full "text" plus display items, such as figures and tables). It may create confusion, as normally users should be citing the landing page, not a specific file format. At least for CrossRef, one should "Ensure that your DOI links resolve to a landing page."[[2]](https://www.crossref.org/documentation/member-setup/creating-a-landing-page/)

Option (c) are items already included in the article main body, such as figures and tables with regular numbering (Fig. 1, Tab. 1), not supplementary numbering (Fig. S1, Tab. S1). I think it could be disabled by default. Notice I've avoided the term "component", as it has a narrower meaning in the context of CrossRef:[[3]](https://community.crossref.org/t/creating-component-registration-xml/2185/2)

> "Components are only intended to be used for supplementary materials (e.g. figures, charts, tables, etc.) that have a single parent-child relationship to some publication."

I thought the present issue #6062 would be a good opportunity to disentangle these three types of galleys currently umped together in the CrossRef plugin: (a) supplementary materials, (b) different file formats of the main body, and (c) specific items in the main body.

**Comment by NateWr** [comment]
@fgnievinski I've created a new issue for this suggestion, because Erik is almost done with this one and when he merges the proposed changes we'll close this issue. You can find the new issue at https://github.com/pkp/pkp-lib/issues/7666, and I'll leave an additional comment there.

**Comment by bozana** [comment]
Are we planing to provide any help message when validation errors occur? Does this maybe belong to the TO-DO "Improve DOI submission error feedback" listed above?

**Comment by NateWr** [comment]
We capture the error response from Crossref and set an "error" status on the DOI. The DOI management UI then provides a button to view the error message when a deposit has failed. This is just the XML error message from Crossref, so not always very user friendly, but it's a first step.

**Comment by bozana** [comment]
Thanks a lot @NateWr. In my case: I wanted to _export_ an XML file and got the message that validation error occurred. I am not sure if the validation also happens before the registration with Crossref -- earlier it was so... I then needed to take a look at the XML file in the temp/ folder to see what is wrong... (I think in my case the DOI was not assigned to that object at all)...

**Comment by NateWr** [comment]
Ahh, I'm not sure how validation errors are handled with the XML export option.

**Comment by AhemNason** [comment]
Hey folks, I just wanted to break down the error message and what's useful for us and what's useful for Crossref when helping someone with support. 

![Screen Shot 2022-08-24 at 9 44 58 AM](https://user-images.githubusercontent.com/504276/186421782-f78bb2fe-5150-4971-a555-13553218924c.png)

Of the stuff present here, the biggest one is the error itself, obviously. I don't know that we have, necessarily, _easier or more user-friendly ways to represent this data_ but, I could probably create a list of "layman's terms" answers for common problems and we could match against the error language, if that sounds amenable to folks. 

The only other big pieces here are the submission ID and the batch ID. Probably also timestamp. If we could change the error modal to have like... 

- timestamp
- submission id
- batch id
- error message
- and then a button for "view details" to expand the full json/xml error, that would probably help folks a lot...

To answer bozana's other question, validation can happen _before_ deposit if you've selected the "validate xml" checkbox. This is like a sanity check before deposit or export. It will tell you if something is invalid before an attempt at a deposit.

**Comment by bozana** [comment]
Thanks @AhemNason. I know it was so earlier, but with the new changes I do not know when it happens -- I would need to take a deeper look in the code...

Those validation errors are 'impossible' to make user friendly :-( -- It can be anything... But...

**Comment by AhemNason** [comment]
Could Crossref perhaps be of assistance in pushing us less wild error messages somehow?

**Comment by ewhanson** [comment]
All steps outlined in this meta issue have been addressed! :tada:
