### ISSUE TITLE
[UI] Frontend issues

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#639]
The following are outstanding issues in the new UI related to the frontend.

- [x] Only right sidebars work! (main content panel needs a `float: right` when only a left sidebar exists... may not work with 2 sidebars) See [PR#561](https://github.com/pkp/ojs/pull/561)
- [x] ~~If no footer categories/links exist, there's still a gray bar across the bottom of the screen.~~

**Register/Login**
- [x] Register and login not styled yet. Woops! See [PR#658](https://github.com/pkp/pkp-lib/pull/658) and [PR#560](https://github.com/pkp/ojs/pull/560)
- [x] The location of the "forgot password" link disrupts the expected flow when navigating via keyboard. Probably needs to go down to the bottom. #1443

**Navigation**
- [x] Dropdown menus can exceed the viewport.
- [ ] ~~The user nav relies on jQuery UI for some reason. If we can get rid of this we'll be able to jettison one more frontend dependency.~~

**Issues/Article Overviews**
Critical issues for 3.0b are filed in #659.
- [ ] ~~Issues always show TOC instead of issue covers. Not sure how to turn off `$showToc`. I'd recommend we get rid of the option and just show issue covers in `issueArchive.tpl` and `issue_toc.tpl`.~~
- [ ] Can't (yet) add an article cover, so they haven't been tested or styled.
- [ ] Test per-article settings for hiding the author.

**Journal Index**
- [x] Lots of extraneous options for the homepage can go away. Then we need to discuss what a good homepage would do and what a sane collection of information there might be.

**Article Details**
- [x] Lots of room to improve the design here once all the components are in place
- [x] Missing items #661
- [x] ~~The section and issue details could be displayed better. Also, instead of using the section name for an article, use the "Display Article As" setting.~~
- [ ] ~~Maybe use schema.org markup? Need to check if this conflicts with any Google Scholar markup.~~

**Search**
- [x] Untouched templates. #662
- [ ] Badly in need of a complete rewrite and restructure in the markup and styles. The handler could take a lot more of the logic load too, to help clean up the templates (especially the filters)
- [ ] instantSearch is not implemented in any way
- [ ] Date filters could use date pickers of some kind, maybe? Maybe not for historical searches
- [ ] Journal and Issue data in search results needs some better thought on presentation (as do the results in general)

**About/Submissions**
- [ ] ~~Recommendation: Minimize all the different input fields that make up the about page as much as possible. One textarea to rule them all. Even sponsors/contributors and contact details can just as easily be put into a textarea.~~ Implemented.
- [ ] ~~Use schema.org markup on contact details~~
- [ ] ~~The link for Author Guidelines doesn't work. Throws an `assert` error in server logs.~~

**Sidebar Blocks**
- [ ] ~~Test custom block, externalFeed, webFeed, lucene, and announcementFeed block plugin styles. ~~See #1390

**Misc**
- [x] Announcements try to open in modal, which fails because there's no modal on the frontend. Needs complete revision. Let's get these out of the grid so we can display them like news items, even give them their own URL.
- [ ] ~~`about/aboutThisPublishingSystem.tpl` hasn't been reworked yet. There's a new image to go in there. *This was refactored but still needs the new image.* Now at `/frontend/pages/aboutThisPublishingSystem.tpl`~~
- [ ] ~~`about/history.tpl` exists, but not sure how to call it or whether it's still in use.~~
- [ ] ~~Page titles in the head `<title>` tag should add the journal name after the page title name. SEO ftw!~~ See #1390 
- [ ] ~~Use schema.org markup when describing the site if a journal object exists and can be used in a sane way.~~
- [x] No longer using `linkToEditPage.tpl`. We use a component in OJS `/frontend/components/editLink.tpl`. Check for use in OMP then either remove `linkToEditPage.tpl` or move our new component into lib/pkp and update everything. See #717 
- [ ] The handler which handles the For Readers urls also handles two ops I couldn't figure out how to load: `competingInterestGuidelines` and `sampleCopyrightWording`
- [ ] ~~OMP uses the same `information/information.tpl` setup, but also passes a `$contentOnly` parameter. Not sure what how this is used.~~
- [ ] ~~There's a template in OJS `information/information.tpl` that does nothing but load the same template in `lib/pkp.~~
- [ ] It'd be nice if login/registration were done in a modal on the frontend with a very nice flow. A slick presentation of this process can make a strong first impression.

**Footer**
- [x] ~~Turn it into a sidebar if we can?~~
- [x] ~~Footer link category titles link to a page on the backend that seems pretty useless...
Speculation~~
- [x] What goes into the sidebar? Right now, it seems like all of those things would be better placed in a footer. Lots of interesting possibilities open up on article, search and homepages if we got rid of the left/right sidebar. Maybe only something for another theme, but something to consider.
- [ ] Any chance we could make these functions: `getBestArticleId(); getBestIssueId(); getBestGalleyId()` follow a common naming pattern, like `getBestId()`? It could reduce some lingering logic in the templates.

**Template Structure**
- [ ] ~~Although all of the OJS frontend templates have been put into the `/templates/frontend/` structure, there are still some lingering templates in `pkp-lib` that could be organized similarly: `common/frontend/*.tpl`, `information/information.tpl`~~

**Comment by NateWr** [comment]
I've had a look through and everything important is covered in other issues. Closing.
