### ISSUE TITLE
QuickSubmit plugin enhancements and bugs meta issue

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7446]
This meta issue is a collection of currently outstanding issues related to bugs, feature suggestions, UI/UX changes, and enhancements for the QuickSubmit plugin as of November 2021. 

Some common threads and priorities identified from the following issues include:

- [ ] How submission object creation within the QuickSubmit plugin is handled
- [ ] Assigned publication dates not working as expected or desired
- [ ] Requested changes to author metadata requirements

### Enahncements and UI/UX Improvements

These include desired changes to existing behaviour and workflow as well as added functionality.

- #7229
    - Contingent on completion of #7191
- #7224
    - Necessary behaviour for current architecture but could be refactor
- #7165
- #6652
- #6528
    - Related to creation of incomplete submissions
- #6125
- #5823
- #5418
- #5131
- #3561
- #7394

### Bugs

These include functionality that does not work as intended or restricts usage of the plugin.

- #6927
- #6294
- #5502

### Issues identified in previous versions

These include issues that outline behaviour present in previous versions that require confirmation on whether these issues persist.

- #2644
- #2246
- #4950
- #4621
- #3639
- #2645

**Comment by mpbraendle** [comment]
@NateWr  3.6 milestone? Wait another three years to fix some essential problems (e.g. https://github.com/pkp/pkp-lib/issues/2644 , that exists since 2017 )?

**Comment by NateWr** [comment]
When this work can be done depends on our priorities and capacity. Our priorities are a mixture of user requests and grant funding for specific projects. You can see an overview of the development schedule in our [roadmap](https://pkp.sfu.ca/roadmap).

This is one of those that we really wanted to get into 3.5, but couldn't justify scheduling it in given our current capacity.

**Comment by jonasraoni** [comment]
At the [#7709](https://github.com/pkp/pkp-lib/issues/7709), we've got an issue related to the https://github.com/pkp/pkp-lib/issues/6011.
The [current code](https://github.com/pkp/pkp-lib/blob/480c1515b4d5db219ceb6f9699a3cfb5f658fda6/classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.inc.php#L383) is using the following check to consider if the submission is imported `submission.date_submitted > publication.date_published`, but valid cases might escape from it (a submission created and published on the same day).

I've suggested to add a `is_imported` field. Another alternative would be to check if the submission has at least one decision, but OPS would fail, as it publishes the submission without creating an accepted decision.

Extra:
I didn't inspect the reasoning, but perhaps the `date_published` should be converted to datetime.

**Comment by jonasraoni** [comment]
About the `is_imported` suggestion, there's an issue to track this type of information here: https://github.com/pkp/pkp-lib/issues/7859

**Comment by ajnyga** [comment]
Noticed that if a journal has no Sections (which is of course something that we maybe should not allow at all?) the Quicksubmit plugin will throw a 500 error.
