### ISSUE TITLE
List of functionality to test before 3.4 release

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8236]
This issue collects/maintains the list of things that needs to be tested before 3.4 release:
- [x] GoogleAnalytics (UA or GA4)
- [ ] Usage stats migration
- [ ] Usage stats log file conversion
- [ ] Usage stats monthly reprocessing, 
- [ ] Usage stats normal daily logging and stats compilation
- [ ] COUNTER (v4 and v5) 
- [ ] Crossref (export, registration)
- [ ] Editorial Decisions
  - [ ] Can record all pre-existing decisions
  - [ ] Emails sent to correct recipients for submissions with 0, 1 or many authors and 0, 1 or many reviewers.
  - [ ] All files promoted to the correct place with the correct decisions
  - [ ] Can "revert" decisions and go back to previous step.
  - [ ] Recommend-only editors can only recommend decisions.
 - [ ] Submission Wizard
   - [ ] All the fields appear or not in the submission wizard depending on configuration settings.
   - [ ] Error messages appear for missing required files and information.
   - [ ] Autosave works if I temporarily lose my internet connection.
   - [ ] Can save for later and return without losing any data.
   - [ ] Can change the language or section after starting a submission.
   - [ ] Submitting not allowed to inactive sections or sections configured to prevent submissions.
   - [ ] After submitting, the correct editors and authors are assigned.
 - [ ] Email Templates
   - [ ] Every template I add to the Discussion emails appears when I try to create a discussion in that stage.
   - [ ] When editing an email template, I can use variables, like `{$journalTitle}`. All variables are described clearly.
   - [ ] After upgrading from a real 3.3.0-x database, automated emails like the journal health report and the editorial reminder are sent to the correct recipients, and the information in the emails is correct.
   - [ ] After upgrading from a real 3.3.0-x database, no email templates include incorrect email variables.
- [ ] Tests to send emails through Google/Gmail API, see https://github.com/pkp/pkp-lib/issues/8673

**Comment by bozana** [comment]
I think we can close this issue...
