### ISSUE TITLE
JII Masthead

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8957]
Masthead roles management:
- [x] As JM I would like to define masthead service roles, by default these will be there: Editor in Chief, Associate Editor, Section Editor, Book Review Editor, Special Issue Editor, Editorial Board Member, Reviewer. -- JM can define if a role will be consider for masthead, and JM can change the name of the role. (s. https://github.com/pkp/pkp-lib/issues/9552 and https://github.com/pkp/pkp-lib/issues/10620)
- [x] As JM I would like to define the order of masthead service roles, in which they will be publicly listed. The users will then be listed alphabetically. S. https://github.com/pkp/pkp-lib/issues/9736.

Masthead management:
The following items will be implemented as part of this issue: https://github.com/pkp/pkp-lib/issues/3022
- [x] As JM I would like to search users by OJS role and name, to invite an existing user to be part of the masthead in a specific role, and to be publicly listed as such. 
- [x] As JM I would like to see the date when an existing user was invited to be part of the masthead.
- [x]  As a user I would like to accept or decline the invitation to serve in a specific editorial role and to be listed on part of the masthead as such, along with my affiliation and ORCID.
- [ ] As JM I would like to be informed/see if an user that was invited to be part of the masthead accepted or declined the invitation.
- [ ] ~~As JM I would like to add an user to be part of the masthead, defining start date and role.~~ (as decided the masthead will be automatically created)

The following items are closely connected/part of this issue: https://github.com/pkp/pkp-lib/issues/7406
- [ ] As JM I would like to ask an user to enter and authenticate ORCID + to grant access for the organization (= journal or publisher as ORCID member) to read and update their ORCID record.
- [ ] When a masthead service is created for an user, the user’s ORCID record will be updated. (s. https://github.com/pkp/pkp-lib/issues/7406)

The following items are part of this issue: https://github.com/pkp/pkp-lib/issues/9271
- [x] ~~As JM I would like to edit a masthead service (e.g. to correct the role, start or end date)?~~ This is not possible -- the role, start and end date are defined by the invitation and cannot be changed any more. The invitation is either accepted as is, or a new invitation needs to be made.
- [ ] As JM I would like to thank the user and end an active masthead service, defining the end date.
- [x] As JM I would like to see all active masthead services (s. public masthead https://github.com/pkp/pkp-lib/issues/9860).
- [x] ~~When a user is disabled all active masthead services will be ended for that user.~~ Disabling a user functions differently -- currently no roles are ended, and the user can be reactivated again. Thu disabling a user will not end the masthead services.
- [x] If a user is removed all masthead services will be ended for that user.
- [x] If a user is merged with another user, and thus fully removed form the system, also all masthead services will be deleted for that user.
- [x] When a reviewer submits a review, the reviewer should be assigned to that year for the masthead (s. public masthead https://github.com/pkp/pkp-lib/issues/9860).

Masthead publication/display:
- [x] The active masthead services will be publicly displayed by role, name, affiliation, ORCID, start date, with the order of roles, as it applies: Editor-in-Chief, Associate Editor, Section Editor, .Book Review Editor, Guest Editor, Editorial Board Member. -- The order of roles will be defined by JM, s above. (s. https://github.com/pkp/pkp-lib/issues/9860)
- [x] The last year reviewers will be listed on the active masthead page. (s. https://github.com/pkp/pkp-lib/issues/9860)
- [x] The ended masthead services will be publicly displayed.

Editorial history:
- [x] As JM I would like to be able to enter the masthead old history, as text (e.g. in a text input field or a static page) i.e. not using the current masthead functionality, that will be publicly displayed.

**Comment by bozana** [comment]
The two points above are still open, because they are closely connected to the invitation workflow, and that is now solved differently.
I will close this meta issue, and if any changes need to be done, new issues should be open.
