### ISSUE TITLE
OJS/OMP/OPS 3.5.0 Change Orientation

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9276]
## For the Release Notebook ##

Items needing addition to the 3.5.0 Release Notebook should be noted here.
- [x] Invitations toolset https://github.com/pkp/pkp-lib/issues/9197
- [x] Slim API endpoints moved to Laravel https://github.com/pkp/pkp-lib/issues/7698#issue-1132905079
- [ ] Hook self-documentation https://github.com/pkp/pkp-lib/discussions/8089#discussioncomment-7139458
- [x] The Stringy dependency has been removed in favour of Laravel's `Str`; many PKPString wrapper functions have been removed
- [x] Add documentation note for those who are upgrading on how to add an app key (https://github.com/pkp/pkp-lib/issues/9895 -- see release notes)
- [x] Add documentation note about new API endpoint hook and how to add/modify API endpoint from plugin (https://github.com/pkp/pkp-lib/issues/9434)
- ...`_codesafe` [string wrapper functions removed](https://github.com/pkp/pkp-lib/issues/10164) (no longer necessary due to PHP8.2 baseline)
- Previously deprecated behaviours removed:
  - [x] `.inc.php` file suffixes are no longer supported
  - [x] Use of `HANDLER_CLASS` no longer supported
  - [x] All calls to `Router::url` or `Dispatcher::url` should use `array`s for the `$path` parameter -- scalars no longer supported
  - [x] Non-namespaced plugins are no longer supported.
- [x] The `fatalError` error handling function has been removed; use exceptions instead.
- [x] Email logging now uses an Eloquent model in place of a DAO (https://github.com/pkp/pkp-lib/issues/10129).
- [x] Notes (https://github.com/pkp/pkp-lib/issues/10188) and Queries (https://github.com/pkp/pkp-lib/issues/10189) now use Eloquent models in place of a DAO.
- [x] UserGroup now uses an Eloquent model in place of a DAO (https://github.com/pkp/pkp-lib/issues/10506).
- [x] Add documentation about new scheduler tool with new configs and deprecation of XML based tasks along with deprecation of Acron Plugin (https://github.com/pkp/pkp-lib/issues/9678) [comment](https://github.com/pkp/pkp-lib/issues/9678#issue-2110219392)
- [x] Add documentation about deprecation of `Services` and `PKPServices` classes and moving the service classes resolving via laravel container (https://github.com/pkp/pkp-lib/issues/9913)
- [x] Add documentation about the new config and control mechanism to process queue jobs via schedule tasks (https://github.com/pkp/pkp-lib/issues/9823)
- [x] New URL paths for frontend JS dependencies: https://github.com/pkp/pkp-lib/issues/9753
  - [x] jQuery: `js/build/jquery/`
  - [x] jQuery UI: `js/build/jquery-ui/`
  - [x] jQuery Validation: `js/build/jquery-validation/`
  - [x] ChartJS: `js/build/chart.js/`
- [x] We now use Weblate languages (s. https://github.com/WeblateOrg/language-data/blob/main/languages.csv), so that the locales changed like this (s. https://github.com/pkp/pkp-lib/issues/9707):
'be@cyrillic' => 'be',
'bs' => 'bs_Latn',
'fr_FR' => 'fr',
'ja_JP' => 'ja',
'nb' => 'nb_NO',
'pt_PT' => 'pt',
'sr@cyrillic' => 'sr_Cyrl',
'sr@latin' => 'sr_Latn',
'uz@cyrillic' => 'uz',
'uz@latin' => 'uz_Latn',
'zh_CN' => 'zh_Hans',
- [x] There are new configuration options in `config.TEMPLATE.inc.php` for caching; see https://github.com/pkp/pkp-lib/issues/7111
- [x] Add documentation about deprecated controlled vocab DAO classes along with new mechanism to retrieve/insert and ability to support external vocab source https://github.com/pkp/pkp-lib/issues/10292 
- [x] Affiliation tag changes for User import/export and authors in Native import/export (https://github.com/pkp/pkp-lib/pull/10963)
- [x] Locales are now part of the URLs (https://github.com/pkp/pkp-lib/issues/699)
- [ ] GoogleScholarPlugin::references hook now gets an array of citations instead of array of raw citations

### Frontend Editorial Tech stack changes
- [x] Vue2 -> Vue3 migration - https://github.com/pkp/pkp-lib/issues/8919
- [ ] Vue Options API deprecated in favour of new Composition API - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-technical-roadmap--docs#vue3-composition-api-35
- [ ] Deprecating use of smarty on new/updated editorial pages - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-technical-roadmap--docs#vuejs--smarty---vuejs-35
- [ ] Updated page architecture - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-page-architecture--docs
- [ ] Introducing UI Guide for plugins for editorial UI to use custom Vue.js components - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-plugins--docs
- [ ] Deprecating mixins in favour of composables - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/composables-usefetch--docs
- [ ] Easy use of translations in Vue.js components, without manual passing via props - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-translation--docs
- [ ] Adopting tailwindcss for building new editorial UI - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-style-introduction--docs
- [ ] Deprecating ListPanel component in favour of Table component for new Listings/Managers - https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/components-table--docs , Example: https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/managers-reviewermanager--docs

### Breaking changes in the editorial UI
- [ ] [Dashboard](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/pages-dashboard--docs) and [Workflow](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/pages-workflow--docs) pages follow the architecture explained above. Therefore if you used hooks to extend them, please checkout new [Plugins guide](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-plugins--docs) to see how to migrate towards JS Hooks.

- [ ] Also new [FileManager](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/managers-filemanager--docs), [ReviewerManager](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/managers-reviewermanager--docs), [ParticipantManager](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/managers-participantmanager--docs) and [GalleyManager](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/managers-galleymanager--docs) managers are using new architecture.  If you need to add column or action, also please follow [Plugins guide](https://stable-3_5_0--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/guide-plugins--docs) . Note that most of the modals that these managers open are still on the old stack rendered in PHP, therefore any plugin extensions within modals should work as before.

## For Documentation ##

Items that will require documentation updates should be captured here.

(TBD: Review the issue list and populate)

### All Applications

- Ability to bulk-delete incomplete submissions (https://github.com/pkp/pkp-lib/issues/6528)

### OJS-specific

- Issue publication date changes (https://github.com/pkp/pkp-lib/issues/7165)
  - You can now set an issue's Published Date before actually publishing the issue. If no date is specified, OJS will automatically assign the current date when the issue is published.
  - When an issue is published, any articles (publications) assigned to that issue will automatically inherit the issue’s Published Date, unless the article already has its own publication date set in the publication metadata settings.
  - If you publish an article without a set publication date in an already published issue, the article will get the current date (continuous model)

### OMP-specific

- The ONIX schema version has been updated for OMP. In some metadata fields (e.g. for Publication Formats or Marketing), metadata values in lists will appear as "Discontinued". This means they have been deprecated in the Onix schema and should no longer be used, but are included for backwards compatibility.

**Comment by asmecher** [comment]
@jardakotesovec, there are a bunch of things here that are UI-related changes; are these sufficiently covered in Storybook, or should they be considered in the [3.5 Release Notebook](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.5-release-notebook)?

**Comment by jardakotesovec** [comment]
@asmecher Its all covered in storybook, but I think its useful still to list these and point for details in storybook. 

All items I could think of I did add to the **Breaking changes in the editorial UI** and **Frontend Editorial Tech stack changes**
